Repository jsunbin/github-flow-test, pull requests merged in 2023-06, with the labels that each got.

#3 feat: 로그인 기능 추가 #2
  src/login.js
Labels: feat

#10 [design]index.css 추가
  index.css
Labels: docs

#14 Revert "[refactor]판매페이지 App.js 코드 개선#12"
  src/App.js
Labels: bug

#16 [feat] 어쩌구 기능추가
  src/App.js
  src/join.js
Labels: feat

#18 [design] 홈 피드 마크업 #17
  index.css
Labels: design

#21 [add] assets/images에 svg 이미지 추가 #20
  src/assets/images/icon-home.svg
  src/assets/images/icon-image.svg
Labels: add
